package bigquery

import (
	"context"
	"fmt"
	"strings"

	datatransfer "cloud.google.com/go/bigquery/datatransfer/apiv1"
	"cloud.google.com/go/bigquery/datatransfer/apiv1/datatransferpb"
	"google.golang.org/api/iterator"
	"google.golang.org/api/option"
	"google.golang.org/protobuf/types/known/fieldmaskpb"
	"google.golang.org/protobuf/types/known/structpb"
)

// Scheduler manages BigQuery Data Transfer scheduled queries.
type Scheduler struct {
	SAKeyFile string
}

// BuildScheduledSQL generates the SQL for the scheduled query.
// This reads from the metadata table at runtime so new sources are automatically included.
func BuildScheduledSQL(destProject, destDataset, destTable, metadataTable string, days int) string {
	if days <= 0 {
		days = 3
	}

	// The scheduled query uses a scripting approach:
	// 1. Read active sources from the metadata table
	// 2. Build dynamic UNION ALL
	// 3. DELETE recent + INSERT fresh
	//
	// Since BQ scheduled queries don't support dynamic SQL easily,
	// we generate static SQL from the current source list.
	// When sources change, the schedule should be updated.
	return fmt.Sprintf(`-- Auto-generated by billing-consolidator schedule command
-- Re-run 'billing-consolidator schedule' after adding new sources

DECLARE cutoff TIMESTAMP DEFAULT TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL %d DAY);

DELETE FROM `+"`%s.%s.%s`"+`
WHERE usage_start_time >= cutoff;

-- Sources are injected statically from billing_export_sources at schedule creation time
-- INSERT statement will be appended by the schedule command
`, days, destProject, destDataset, destTable)
}

// BuildScheduledQuerySQL builds the complete scheduled query SQL with static source references.
// If merged and schemas are provided, uses explicit column lists to handle schema differences.
func BuildScheduledQuerySQL(destProject, destDataset, destTable string, sources []SourceRecord, days int, merged *MergedSchema, schemas []*TableSchema) (string, error) {
	if len(sources) == 0 {
		return "", fmt.Errorf("no active sources for scheduled query")
	}
	if days <= 0 {
		days = 3
	}

	destRef := fmt.Sprintf("`%s.%s.%s`", destProject, destDataset, destTable)

	var unions []string
	for i, s := range sources {
		ref := BuildSourcesFullRef(s)
		if merged != nil && schemas != nil {
			selectExpr := BuildSelectExpr(merged, schemas[i])
			unions = append(unions, fmt.Sprintf("  SELECT %s FROM %s WHERE usage_start_time >= cutoff",
				selectExpr, ref))
		} else {
			unions = append(unions, fmt.Sprintf("  SELECT * FROM %s WHERE usage_start_time >= cutoff", ref))
		}
	}

	sql := fmt.Sprintf(`DECLARE cutoff TIMESTAMP DEFAULT TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL %d DAY);

DELETE FROM %s
WHERE usage_start_time >= cutoff;

INSERT INTO %s
%s;`,
		days, destRef, destRef, strings.Join(unions, "\nUNION ALL\n"))

	return sql, nil
}

// CreateOrUpdateSchedule creates or updates a BQ Data Transfer scheduled query.
// serviceAccountName is the email of a service account to run the query as (required when using ADC).
func (s *Scheduler) CreateOrUpdateSchedule(ctx context.Context, projectID, datasetID, displayName, sql, cron, serviceAccountName string) (string, error) {
	var opts []option.ClientOption
	if s.SAKeyFile != "" {
		opts = append(opts, option.WithCredentialsFile(s.SAKeyFile))
	}

	client, err := datatransfer.NewClient(ctx, opts...)
	if err != nil {
		return "", fmt.Errorf("creating data transfer client: %w", err)
	}
	defer client.Close()

	parent := fmt.Sprintf("projects/%s/locations/us", projectID)

	// Check if a transfer config with this display name already exists
	existingID, err := s.findExistingConfig(ctx, client, parent, displayName)
	if err != nil {
		return "", err
	}

	params, err := structpb.NewStruct(map[string]interface{}{
		"query": sql,
	})
	if err != nil {
		return "", fmt.Errorf("creating params: %w", err)
	}

	if existingID != "" {
		// Update existing
		req := &datatransferpb.UpdateTransferConfigRequest{
			TransferConfig: &datatransferpb.TransferConfig{
				Name:         existingID,
				DisplayName:  displayName,
				DataSourceId: "scheduled_query",
				Schedule:     cron,
				Params:       params,
			},
			UpdateMask: &fieldmaskpb.FieldMask{
				Paths: []string{"display_name", "schedule", "params"},
			},
			ServiceAccountName: serviceAccountName,
		}
		config, err := client.UpdateTransferConfig(ctx, req)
		if err != nil {
			return "", fmt.Errorf("updating scheduled query: %w", err)
		}
		return config.Name, nil
	}

	// Create new — no destination_dataset_id since we use scripting (DECLARE/DELETE/INSERT)
	req := &datatransferpb.CreateTransferConfigRequest{
		Parent: parent,
		TransferConfig: &datatransferpb.TransferConfig{
			DisplayName:  displayName,
			DataSourceId: "scheduled_query",
			Schedule:     cron,
			Params:       params,
		},
		ServiceAccountName: serviceAccountName,
	}
	config, err := client.CreateTransferConfig(ctx, req)
	if err != nil {
		return "", fmt.Errorf("creating scheduled query: %w", err)
	}
	return config.Name, nil
}

func (s *Scheduler) findExistingConfig(ctx context.Context, client *datatransfer.Client, parent, displayName string) (string, error) {
	it := client.ListTransferConfigs(ctx, &datatransferpb.ListTransferConfigsRequest{
		Parent:        parent,
		DataSourceIds: []string{"scheduled_query"},
	})
	for {
		config, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return "", fmt.Errorf("listing transfer configs: %w", err)
		}
		if config.DisplayName == displayName {
			return config.Name, nil
		}
	}
	return "", nil
}
